lblod/app-lpdc-digitaal-loket

- docker-compose.yml
Remove the Virtuoso compatibility layer and bump the Virtuoso image to use the `latest` tag for the time being. This fixes the bugs stemming from conflicting boolean types. After conducting some tests, it seems the issues are gone, and there is no more need for the compatibility layer anymore.
I'll merge this PR for now, and assign numbered tags to the virtuoso images once a new tag is released.
> Remove compatibility layer and use latest Virtuoso

- config/migrations/2023/20230707142328-remove-wasInGraph-predicate.sparql
This predicate was added when exporting date from Loket in order to re-import bestuurseenheden, person and accounts back to their correct graphs; it is now no longer needed.
> Remove wasInGraph predicate

- config/migrations/2024/20240806132638-fix-incorrect-competent-authority-uri-gent.sparql
For a while Ghent's LDES contained incorrect URIs to refer to organisations in
the organisatieregister. More specifically, the URIs where defined as
`http://data.lblod.info/id/bestuurseenheden/OVOXXXXXX`
instead of
`https://data.vlaanderen.be/id/organisatie/OVOXXXXXX`.
On their side, Ghent already corrected the URIs in their LDES.
This migration corrects the faulty URIs on LPDC's side for:
1. Any product or service that uses a faulty URI to refer to a competent
authority and/or executing authority. If a service was already published its
status is also updated such that the `lpdc-publish-service` will re-publish
it.
2. Any faulty resource URI in the public graph such that the
`lpdc-management-service` constructs correct code lists for competent
authorities.
- LPDC-1260
- LPDC-1268
> fix: correct faulty OVO code URIs for organisations

- tests/docker-compose.tests.development.yml
As @mirdono mentioned [in a PR on the lpdc-management-service](https://github.com/lblod/lpdc-management-service/pull/44), the image version for the tests in the app also need to be changed back to the `mu-javascript-template`.
> Back to `mu-javascript-template`

- docker-compose.yml
LPDC previously used a feature branch of `mu-cl-resources` which occasionally
seems to cause problems with organisation's products/services not loading. As a
quick fix the service was already bumped on production via override. This PR
is intended to make this a permanent bump.
Related to LPDC-1303
> chore: bump `mu-cl-resources`

- config/migrations/2024/20241107114207-import-municipalities-and-ocmws-with-new-kbo-mergers-2025/20241107114207-import-municipalities-and-ocmws-with-new-kbo-mergers-2025.graph
- config/migrations/2024/20241107114207-import-municipalities-and-ocmws-with-new-kbo-mergers-2025/20241107114207-import-municipalities-and-ocmws-with-new-kbo-mergers-2025.ttl
Import the merged municipalities and OCMWs that are assigned new URIs. The data
is extracted from Loket and extended with LPDC-specific data.
This concerns four municipalities and their OCMWs:
1. Beveren-Kruibeke-Zwijndrecht: merger of municipalities Beveren, Kruibeke and Zwijndrecht
2. Nazareth-De Pinte: merger of municipalities De Pinte and Nazareth
3. Pajottegem: merger of municipalities Galmaarden, Gooik and Herne
4. Merelbeke-Melle: merger of municipalities Melle and Merelbeke
These organisation have previously been added to, at least, OP and Loket but
since LPDC does not automatically synchronise with these apps a manual creation
of the organisations is required.
Extracted from Loket (production):
- URI
- type: `besluit:Bestuurseenheid`
- name: `skos:prefLabel`
- identifiers: …
> chore: import merged municipalities and OCMWs with new URIs

- config/migrations/2024/20241106152035-update-codelist-spatials-nuts-lau/20241106152457-import-nuts2024-codelist.ttl
The NUTS LAU 2024 code list was initially imported in full in #34. The presence
of language tagged `skos:prefLabel`s causes the frontend to show duplicate
options and English labels in the relevant drop down list.
1. Log in to LPDC (with test or dev data) as any organisation with product
instances.
2. Select a product instance from the list, any will do.
3. If the selected product has the status “Verzonden”, click the “Product
opnieuw bewerken” button at the top of the page. On the warning that appears,
click the button with the same text.
4. Open the "Eigenschappen" tab for the select product instance.
5. Go to the “Bevoegdheid” section, this contains the field "Geografisch
toepassingsgebied" whose values match the NUTS code list resources.
There are two issue:
- Most municipalities will …
> fix: remove English labels and definitions from NUTS code list

- config/migrations/2024/20241106152035-update-codelist-spatials-nuts-lau/20241106152457-import-nuts2024-codelist.ttl
The 2024 NUTS code list uses the same label for different codes when the
relevant municipality is involved in a merger but does not changes its
name. This results in seemingly duplicate options when a user tries to select a
product's scope (nl. Geografisch toepassingsgebied).
1. Log in to LPDC, any organisation with product instances will do.
2. Select a product instance from the list, any will do.
3. If the selected product has the status “Verzonden”, click the “Product
opnieuw bewerken” button at the top of the page. On the warning that appears,
click the button with the same text.
4. Open the "Eigenschappen" tab for the select product instance.
5. Go to the “Bevoegdheid” section, this contains the field "Geografisch
toepassingsgebied" whose values match the NUTS code list resources.
6. …
> fix: avoid duplicate scope options for products

- CHANGELOG.md
- config/migrations/2024/20241112145534-add-merger-mock-accounts/20241112145534-add-merger-mock-accounts.sparql
- config/migrations/2024/20241112145534-add-merger-mock-accounts/20241112145535-add-concept-display-configurations-for-ocmw-and-gemeente-pajottegem.sparql
LPDC-1291
This PR adds mock login accounts/persons to the new fusiebestuuren.
Go to `/mock-login` and search for the following:
* `Merelbeke-Melle`
* `Beveren-Kruibeke-Zwijndrecht`
* `Nazareth-De Pinte`
* `Pajottegem`
These labels correspond to both new Gemeenten and OCMWs, so there will be a total of 8 new users.
Click on some of them => You should see an empty page.
**TODO**: Check if concept consume testing needs to happen in this PR as well.
> Add mock person and account for new fusies

- config/migrations/2024/20241129182951-add-werkingsgebieden-for-new-fusies.sparql
LPDC-1332
This PR allows new fusiebesturen to have the `Geografische Toepassingsgebied` section immediately be prefilled with the area they are in.
* Log in as `Gemeente Pajottegem` for example.
* Add any random service.
* Go to the `Eigenschappen` section of the form => You will see that the field is missing.
* Check out this branch and run the migration.
* Perform the same steps and add a new service.
* You will the field is now filled with `Pajottegem`.
> Add werkingsgebieden for new fusies

- docker-compose.yml
This PR bumps `migrations` to `v0.9.0`.
Run the migrations of this repo from scratch => Migrations should complete without issues.
> Bump migrations service to v0.9.0

- CHANGELOG.md
- config/migrations/2025/20250114112818-import-organisation-statuses/20250114112818-import-organisation-statuses--concept-scheme.graph
- config/migrations/2025/20250114112818-import-organisation-statuses/20250114112818-import-organisation-statuses--concept-scheme.ttl
- config/migrations/2025/20250114112818-import-organisation-statuses/20250114131511-import-organisation-statuses--organisation-status-data.graph
- config/migrations/2025/20250114112818-import-organisation-statuses/20250114131511-import-organisation-statuses--organisation-status-data.ttl
- config/migrations/2025/20250114112818-import-organisation-statuses/20250114135204-import-organisation-statuses--copy-organisation-status-data-to-public-graph.sparql
For new functionality, LPDC requires status information for organisations. This PR imports this data from OP, which the master for that data.
The concept scheme and concepts for organisation statuses were exported from OP (PROD) using the following query (the retrieved URIs `?s` were manually determined):
``` sparql
CONSTRUCT {
?s ?p ?o.
} WHERE {
GRAPH <http://mu.semte.ch/graphs/public> {
?s ?p ?o.
}
VALUES ?s {
<http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6>
<http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab>
<http://lblod.data.gift/concepts/d02c4e12bf88d2fdf5123b07f29c9311>
<http://lblod.data.gift/concept-schemes/b8dcb04f0d1feb86ff01cc0677363b20>
}
}
```
The actual organisation statuses are also exported from OP (PROD) using the following query:
``` …
```
> chore: import organisation status data from OrganisatiePortaal

- CHANGELOG.md
- config/migrations/2025/20250204101958-insert-authorization-new-integrating-municipalities.sparql
- docker-compose.yml
A new organisation will be integrating with LPDC to allow their clients to manage product instances via their application. This PR sets up LPDC's end to consume the new LDES provided by this organisation.
Configure the correct LDES stream endpoint in `docker-compose.override.yml`, for the DEV and TEST environments this is:
``` yaml
ldes-consumer-instancesnapshot-bct:
environment:
LDES_ENDPOINT_VIEW: "https://igenservicedev.licquid.com/LPDC/v1/InstanceSnapshot?pageNumber=0"
CRON_PATTERN: "*/2 * * * *" # or whatever cronpattern suits your needs
```
- Make sure the migration in PR has executed by (re)starting the migrations service
- Boot the (rest of the) stack and check whether
- the `ldes-consumer-instancesnapshot-bct` service consumes the LDES feed correctly; and
- the `lpdc-management` …
> feat: consume LDES from BCT to integrate additional organisations

- config/migrations/2025/20250214141023-authorise-all-bct-clients-to-publish-via-ldes.sparql
Insert authorisation triples to allow all BCT clients to send product instance snapshots via the new BCT LDES stream.
The query used to obtain the URIs for the organisations:
``` sparql
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?s ?name ?class
WHERE {
GRAPH <http://mu.semte.ch/graphs/public> {
?s a besluit:Bestuurseenheid;
skos:prefLabel ?name;
besluit:classificatie/skos:prefLabel ?class.
}
VALUES (?name ?class) {
("Bilzen-Hoeselt" "Gemeente") # BCT: Bilzen
("Lubbeek" "Gemeente")
("Geel" "Gemeente")
("Geetbets" "Gemeente")
("Oudsbergen" "Gemeente")
("Stabroek" "Gemeente")
("Tielt-Winge" "Gemeente")
("Pelt" "Gemeente")
("Pelt" "OCMW")
("Leuven" "Gemeente") # BCT: Stad Leuven
("Leuven" "OCMW") # BCT: Stad …
```
> feat: authorise BCT clients to send product instances via LDES

- CHANGELOG.md
- docker-compose.yml
LPDC-1339
Fusies will no longer be needed (for now), but will be in the future. Which is why this PR uses a feature flag to show / hide code about the fusies:
- 'Sorteren en filteren': the fusies filter should not be showing anymore
- The fusies pill in the table should not be showing anymore
- The copy button should now directly copy, and not open a popup to choose between fusie and regular
This PR bumps the needed images, and sets their feature flags
> feat: bump images and set feature flags

- CHANGELOG.md
- config/dispatcher/dispatcher.ex
When a user creates a new product instance from a concept, the management
service can update the `conceptIsNew` and `conceptIsInstantiated` properties for
the corresponding concept display configurations. These updates are not picked
up by the cache, resulting in the frontend showing outdated information
afterwards.
Bypass the `mu-cache` service for public service and go directly via the
resources service for public service concepts. This is how it worked before #32.
1. Log in as some organisation in LPDC, any should do.
2. Create a new product using the "+ Product of dienst toevoegen" button in the
top-right corner.
3. In the concept table on the next page, select a concept with a green "Nieuw"
pill behind its name.
4. Take note of the name of the concept.
5. Create a new product …
> fix: do not use cache on route for public service concepts

- CHANGELOG.md
- docker-compose.yml
The LDES consumer was previously use was based on a feature branch. This branch has been merged and a new tagged version of the LDES consumer has been released. The only difference between the previously deployed version and the released one are some edits in the README.
> chore: bump LDES consumer to tagged version

- CHANGELOG.md
- config/migrations/2025/20250325140456-fix--link-organisations-to-nuts2024-spatials.sparql
As part of the 2025 municipality mergers several spatials became invalid as
their municipalities were involved in a merger. For active organisations we
update their werkingsgebieden to link to the new, unexpired spatials. This way
the correct, unexpired spatial is added as geographical area when those
organisations create new product instances.
1. Log in to LPDC as one of the affected organisations, for example Lochristi or
Tongeren-Borgloon (municipality or OCMW should not matter)
2. Create a new product instance using the "+ Product of dienst toevoegen"
button
3. Either create a completely new product instance using the "+ Volledig nieuw
product toevoegen" button. or select a concept from the table and use the "+
Voeg toe button" to create a new product instance
4. In the properties tab …
> fix: link organisations to NUTS2024 spatials

- CHANGELOG.md
- config/migrations/20250404082955-fix--add-concept-type-to-all-ipdcorganisaties.sparql
Not all resources in the IPDCOrganisaties[^1] concept scheme have as type
`skos:Concept`. This causes a query in the management service[^2] to report
inconsistent results. This in turn can lead to false positives when validating
the competent and executing authorities in product instances and product instance snapshots.
- Follow the instructions in the changelog
- Check whether all elements in the IPDCOrganisaties concept scheme have the type `skos:Concept`. Example query that can be used:
``` sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT count(?s)
WHERE {
GRAPH <http://mu.semte.ch/graphs/public> {
?s skos:inScheme <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/IPDCOrganisaties>.
FILTER NOT EXISTS { ?s a skos:Concept. }
}
}
```
[^1]: …
> fix: ensure all elements in IPDCOrganisaties concept scheme are concepts

- CHANGELOG.md
- config/migrations/2025/20250403092249-chore--reset-municipality-merger-labels.sparql
The municipality merger label was hidden for the users by putting its functionality behind a feature flag. This migrations resets the label to its default value for all product instances where it was enabled by users.
- Follow the instruction added to the changelog
- You can check the data with using a query like below. In essence the result should be that the `forMunicipalityMerger` for all product instances should be set to false.
``` sparql
PREFIX ipdc-lpdc: <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#>
SELECT DISTINCT ?o COUNT(?s)
WHERE {
GRAPH ?g {
?s ipdc-lpdc:forMunicipalityMerger ?o.
}
}
```
- LPDC-1403
> chore: reset municipality merger labels on product instances

- CHANGELOG.md
- config/migrations/2025/20250416133525-fix--delete-blank-urls-for-contact-points.sparql
- config/migrations/2025/20250416135555-chore--delete-empty-box-numbers-for-addresses.sparql
Add two migrations to slightly improve the data quality for LPDC. More specifically, this removes URLs for contact points for product instances that are empty strings or contain only whitespace characters. Similarly, box numbers for contact point addresses that contain only whitespace characters are deleted.
This data was most likely added to LPDC when it has less strict validations.
- I opted not to remove similar triples for published product instances[^1]. This would require re-publishing the right versions, introducing additional complications. This complexity does not seem worth it since IPDC processes these blank triple values fine and removing the triples for product instance resources is sufficient for LPDC.
- The ticket contains some further discussion about other URL fields that …
> Delete triples with empty values for contact point URL or address box number

- CHANGELOG.md
- docker-compose.yml
Upgrade the LDES consumer for Ghent's instance snapshot feed to the newest version. This version should be more stable and is actively maintained compare to the one currently used.
Furthermore, this new version correctly supports obtaining the first node/page from the LDES feed itself instead of hardcoding it in the configured viewpoint URL. This allows Ghent to apply a retention policy which may cause the page number of the first page to change over time.
The easiest way to test whether (new) instance snapshot are actually retrieved is to load a production data backup from production your local stack and point the LDES consumer to Ghent's production LDES feed:
1. Obtain and load a backup following your preferred method. At the time of writing the most recent instance snapshots were …
> chore: bump LDES consumer for Ghent

- CHANGELOG.md
- config/migrations/2025/20250814192225-cleanup-empty-contactpoints.sparql
DL-6752
With the changes of https://github.com/lblod/lpdc-management-service/pull/72 we don't create empty contactpoint objects anymore, this migration cleans up any that already exist.
Setup local stack, use `lblod/lpdc-management-service:0.50.5` to still be able to create empty contactpoints.
-> Create instance with a) empty contactpoint, b) empty contactpoint with an empty address as well
-> both a and b should be removed after running the migration
> Add migration to cleanup the empty contactpoints
